UI/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace UI.Controllers
{
    public class SignInController : Controller
    {
        private readonly ILogger<SignInController> _logger;

        public SignInController(ILogger<SignInController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string username, string password)
        {
            var validate = string.Compare(username, "hello@marpha.org") == 0 && string.Compare(password, "admin") == 0;
            if (validate)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

UI/Views/SignIn/Index.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Sign In Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - DonorsDB :: Suported & Maintained by Marpha</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body class="text-center">

    <div class="form-signin" style="padding-top:180px;">
        @using (Html.BeginForm("Index", "SignIn", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <img class="mb-4" src="~/images/Logo.png" alt="" width="92" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Please Sign In</h1>
            <label for="inputEmail" class="sr-only">Email Address</label>

            <input type="email" id="inputEmail" name="username" class="form-control" placeholder="Email Address" required autofocus>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        }
    </div>
    <p class="mt-5 mb-3 text-muted">&copy; 2019-@DateTime.Now.Year | Supported and maintained by <a href="https://www.marpha.org/" target="_blank">Marpha</a>.</p>
</body>
</html>